---
title: "Untitled"
author: "Gráficos"
date: "17/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejemplo gráficos con `plot`

```{r primer_plot, fig.cap="Gráfico de prueba", fig.align='center'}
x2 = c(2,6,4,9,-1)
y = c(1,8,2,-2,3)

plot(x2,y)
```

Si sólo tiene una función contempla que las x son el vector de 1 hasta el numero de resultados introducidos: 

```{r segundo_plot, fig.cap="Gráfico con vector x con 5 valores", fig.align='center'}
plot(x2)
```

Función continua:
```{r}
f <- function(x){sqrt(x)}
plot(f)
```

Escala lineal o logaritmica:
```{r}
par(mfrow = c(1,2))
plot = plot(exp(1:20), xlab="Indice",ylab=expression(e^{1:20}), main="Escala lineal")
plotLog = plot(exp(1:20), log="y", xlab="Indice",ylab=expression(e^{1:20}), main="Escala logaritmica")
par(mfrow = c(1,1))
```

## Uso de parámetros en gráfico

```{r}
par(mfrow = c(1,2))
n = 1:20
fib = (1/sqrt(5))*((1+sqrt(5))/2)^n - (1/sqrt(5))*((1-sqrt(5))/2)^n
plot(fib, pch=21, xlab="n", ylab=expression(F[n]), cex=2,col="orchid1", bg="orchid3", log="xy")
plot(fib, pch=21, xlab="n", ylab=expression(F[n]), cex=2,col="orchid1", bg="orchid3")
par(mfrow = c(1,1))
```

## Parametros de representación del gráfico
```{r}
par(mfrow=c(3,2))
x2 = c(50:59)
y= c(2,9,25,3,100,77,62,54,12,65)
plot(x2,y,pch=23,type="p")
plot(x2,y,pch=23,type="l", lty="dashed", lwd=2)
plot(x2,y,pch=23,type="b")
plot(x2,y,pch=23,type="o")
plot(x2,y,pch=23,type="h")
plot(x2,y,pch=23,type="s")
par(mfrow=c(1,1))
```

## Pintar puntos y rectas en otro gráfico
Funciones points(x,y) y abline().
```{r}
x2 = 2*(1:20)
y = (-1)^(1:20)*5*(1:20)
plot(x2,y,main="Prueba inroducción rayas",pch=8, cex=1, type="b", lty=4,lwd=4, xaxp=c(0,40,2),yaxp=c(-100,100,8))
points(20,0,col="red", cex=2, pch=16)
abline(h=0,lty=2, col="dodgerblue")
abline(5,1,lty="dashed")
abline(h = seq(-100,100,by=25),v = seq(0,40,by=5),lty="dotted")
text(20,10,labels="Circulo rojo", col="red")
lines(8*0:5,4*(0:5)^2,col="green")
curve(x^2,col="orange",add=TRUE)
legend("topright",col=c("blue","green","orange"),legend=c("Uno","Otra",expression(x^2)),lwd=3,bty="l")
```

