---
title: "Ejemplo Final - Cualitativo"
author: "ASR"
date: "29/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1) Agregar datos para pasar de datos tridimensional a dimensional
Quitar el sexo como variable y agrupar.
```{r}
male <- HairEyeColor[,,"Male"]
female <- HairEyeColor[,,"Female"]
data <- as.table(male+female)
data
```

## 2) Cambiar a castellano las keys de los datos
```{r}
dimnames(data) = list(
  Pelo = c("Negro","Marron","Pelirojo","Rubio"),
  Ojos = c("Marrones","Azules","Pardos","Verdes")
)
data

```

## 3) Diagrama de mosaico
```{r}
plot(data,col=c("red"),main="Titulo")
```

## 4) Num. Total en la tabla
```{r}
sum(data)
```

## 5) Tablas de frec. absoltas y relativas por colores de pelo y ojos
```{r}
colSums(data)
rowSums(data)
round(prop.table(colSums(data)),3)
round(prop.table(rowSums(data)),3)
```

## 6) Gráficas de barras
```{r}
barplot(prop.table(colSums(data)),col=c("brown","lightblue","orange3","green"),main="Frec. Relativa ojos")
barplot(prop.table(rowSums(data)),col=c("black","brown","red","yellow"),main="Frec. Relativa cabello")
```

## 7) Frec. Relativa Global

```{r}
round(prop.table(data),3)
round(prop.table(data,margin=1),3)
round(prop.table(data,margin=2),3)
barplot(prop.table(data,margin=1),beside=TRUE,col=c("black","brown","red","yellow"))
barplot(t(prop.table(data,margin=2)),beside=TRUE,col=c("brown","lightblue","orange3","lightgreen"),ylim=c(0,0.5))
```

