---
title: "Python - Colecciones"
author: "ASR"
date: "11/3/2021"
output: html_document
---

# Listas
Contenedores que contienen objetos en orden determinado.
```{python}
L1 = []
L2=['a','b','e','i','o']
L3 = [1,3,4,7,5,8]
L4 = [True,5,'u',"Texto"]
L4[0]

```

Se puede operar con listas o crear listas:
```{python}
L5 = [0]*10
L5[4] = 4
L5
```

## Accesos multiples:
```{python}
L4[0:2]
L5[1:4] = [1,2,3]
L5[3:7]
L5.append(5) # Añadir numeros al final
L5
L5.count(0)
L5.index(2)
```

## Operaciones:
```{python}
L = [1,2,3,4,5,6]
L[1::2] # Del 1 en adelante de 2 en 2
L[-1]
8 in L
```

# Bucles
```{python}
for numero in L:
  print(numero)
  
for x in "Juan":
  print(x)
  
for (y) in range(0,10):
  print(y)
  
for idx,p in enumerate(L):
  print(idx,p)
```

# Tuplas
Coleccion de objetos que no se pueden modificar.
```{python}
tupla = (1,2,3,4)
a,b,c,d = tupla #sacar valores de las tuplas
lista = list(tupla)
lista
tupla2 = tuple(L5)
tupla2
```

# Diccionario


### Ejercicios basicos:
```{python}
persona = {"nombre":"Alex",
           "edad":30,
           "NumPref":2
           }
persona
```

# Librería Numpy

Tipos:
  - bool_ 
  - int_ / intc / intp / int8 / int16 / int32 / int64 / uint8 / uint16 .. 
  - float_ / float16, float32 / float64 (double)
  - complex_ / complex64 / complex128
```{python}
import numpy as np
L1 = [1,2,3,4,5,6,7,8]
np.array(L1,dtype='float32') 
```

Creacion de matrices/vectores:
```{python}
np.zeros((3,4))
np.ones((3,4))
np.arange(10)
np.arange(3,12,dtype=np.float)
np.arange(4,5,.1)
np.linspace(1.,7.,12) # 12 elementos
```

Matriz diagonal:
```{python}
np.eye(5)
x = np.arange(24)
x
x.reshape((6,4))
x.reshape((8,3))
np.ravel(x) # Se modifica el original
x.flatten()
```

Operaciones matrices:
```{python}
y = np.arange(24)
y.reshape((6,4))
np.transpose(y)
```

### Ejercicios
1. Crear array entre 5 y 120
2. Crear matriz 4x4 desde 0 a 15
3. Matriz identidad de 7x7
4. Crear array de 20 elementos y transformarlos a matriz de 5x4
5. Array 20 numeros con valores entre 0 y 5 homogenes
```{python}
x = np.arange(5,120)
x
y = np.arange(0,16)
y.reshape((4,4))
np.eye(7)
z = np.arange(0,20)
z.reshape((5,4))
np.linspace(0,5,20)
```

## Manipulación de Arrays
```{python}
x = np.arange(12)
x = x.reshape((3,4))
x
x.ndim #Dimensiones
x.shape # Forma de matriz como tupla
x.size # Num de elementos
x.dtype # Tipo en la matriz
x.itemsize # Bytes de informacion por elemento
x.data # Posición de memoria de la variable
```
EStas caracteristicas se pueden cambiar:
```{python}
x.shape = 4,3
x[1:3,0:2] # Submatriz
y = np.arange(12)
y[3:8]
y[1:7:2]

z = np.arange(10,6,-1)
z
y[z]

a = np.arange(50)
a[a>30]
cond = a>30
a[cond]
a[5:12] = 2
a
a[2] = 1.34 # Lo pasa a entero porque es el tipo del array
a
```

## Copias y vistas de array
```{python}
x = np.arange(20)
y = x # Referencia
y is x # True is the same
z = x.copy()
z is x # False es copia
```

Vistas de una misma variable:
```{python}
t = x.view()
t
t.shape = (5,4)
t
x
```

Con obtención de un conjunto NO se crea copia:
```{python}
x = x.reshape((4,5))
s = x[0:2,1:3]
s
s[:] = 9
x
```

# Funciones universales (ufunc)
Unarias: Aplicaciones elemento a elemento: sqrt, sin, **2, ...
Binarias: Operaciones con 2 arrays que dan habitualmente otro: maximum, minimum, ...
```{python}
x = np.arange(10)
x+3
x*3
np.power(3,x)
alpha = np.linspace(0,2*np.pi,8)
alpha
np.sin(alpha)
```

Las operaciones de numpy tiene la normal y la libre de valores desconocidos. sum y nansum porque en caso de encontrar de sum da error si hay un NA.
```{python}
np.mean(x)
np.prod(x)
np.min(x)
np.std(x) # Desviación típica
np.var(x) # Varianza de X
np.argmax(x) # El indice del maximo
```

Random
```{python}
np.random.seed(2020) # Si se establece seed será siempre los mismos resultados
z = np.random.random((3,5))
z
z.sum()
z.sum(axis=0) # Por columnas
z.sum(axis=1) # Por filas
```

# Numpy y Algebra lineal

```{python}
M = np.array([[1,2,3],[2,3,4],[7,8,9]])
M
N = np.array([[3,4,5],[1,0,1],[0,7,5]])
N
np.transpose(M)
M.dot(N) # Producto matricial
M.transpose()
M.trace()
np.linalg.matrix_rank(M)
M
np.linalg.inv(M) # Dan numeros muy grandes porque no es invertible
np.linalg.inv(N).dot(N) # Identidad
```

